version: '3'
services:
  # elastic-node1:
  #     image: docker.elastic.co/elasticsearch/elasticsearch:5.5.1
  #     environment:
  #         - bootstrap.memory_lock=true
  #         - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #     ulimits:
  #       nproc: 65535
  #       nofile:
  #         soft: -1
  #         hard: -1
  #     deploy:
  #       resources:
  #         limits:
  #           memory: 1g
  #     volumes:
  #         - elastic-node1-data:/usr/share/elasticsearch/data
  #     ports:
  #         - "9200:9200"

    worker:
        build:
            context: .
            dockerfile: dockerfile
        links:
          # - elastic-node1
          - selenium-hub
          - chrome
          # - firefox
        environment:
          - PYTHONUNBUFFERED=0

    selenium-hub:
        image: selenium/hub
        ports:
          - "4444:4444"

    chrome:
        image: selenium/node-chrome
        links:
          - selenium-hub
        environment:
          - HUB_PORT_4444_TCP_ADDR=selenium-hub:4444/grid/register/
        volumes:
          - /dev/shm:/dev/shm 

    # firefox:
    #     image: selenium/node-firefox
    #     links:
    #       - selenium-hub
    #     environment:
    #       - HUB_PORT_4444_TCP_ADDR=selenium-hub:4444/grid/register/